from __future__ import annotations

import argparse
from pathlib import Path


DIRS = [
    "data",
    "data/policy_document",
    "data/vector_db",
    "source",
    "frontend",
]


FILES = {
    "app.py": """\
# Entry point placeholder.
# Keep FastAPI app object here, then wire routes to source modules.

# Example plan (to be implemented later):
# - load env and startup hooks
# - initialize ephemeral FAISS in data/vector_db
# - expose /api/health and /api/ask
# - mount frontend static assets
""",
    "README.md": """\
# Financial Analyst App Scaffold

This project was generated by scaffold.py.

## Planned layout

- app.py
- data/
  - policy_document/
  - vector_db/
- source/
    - rag_pipeline.py
    - agent_runtime.py
  - schemas.py
  - databasequery.py
- frontend/

## Notes

- vector_db is intended for non-persistent FAISS index artifacts.
- Business logic is intentionally not generated yet.
""",
    "source/__init__.py": """\
# Source package marker.
""",
    "source/rag_pipeline.py": """\
# RAG pipeline placeholder module.
# Add document loading, chunking, embeddings, and retriever logic here.
""",
    "source/agent_runtime.py": """\
# Agent runtime placeholder module.
# Add tool registration and agent invocation orchestration here.
""",
    "source/schemas.py": """\
# Placeholder for Pydantic request/response schemas.
# Add models for API contracts and tool I/O structures.
""",
    "source/databasequery.py": """\
# Placeholder for database query helpers.
# Keep SQL access and query functions centralized here.
""",
    "frontend/README.md": """\
# frontend placeholder

Use this folder for static HTML/CSS/JS pages.
Keep UI code separate from source backend logic.
""",
    "data/README.md": """\
# data folder

Contains runtime and input data assets:
- policy_document/: policy PDFs and source docs
- vector_db/: transient FAISS files (non-persistent intent)
""",
    "data/policy_document/.gitkeep": "",
    "data/vector_db/.gitkeep": "",
}


def write_text(path: Path, content: str, force: bool) -> str:
    if path.exists() and not force:
        return f"SKIP  {path}"

    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content.rstrip() + "\n", encoding="utf-8")
    return f"WRITE {path}"


def build_scaffold(root: Path, force: bool) -> list[str]:
    logs: list[str] = []

    for d in DIRS:
        p = root / d
        p.mkdir(parents=True, exist_ok=True)
        logs.append(f"MKDIR {p}")

    for rel, content in FILES.items():
        logs.append(write_text(root / rel, content, force=force))

    return logs


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Create project scaffold for Financial Analyst App layout."
    )
    parser.add_argument(
        "--root",
        default=".",
        help="Root folder where scaffold should be created (default: current directory).",
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="Overwrite existing placeholder files.",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    root = Path(args.root).resolve()

    logs = build_scaffold(root=root, force=args.force)
    print(f"Scaffold complete at: {root}")
    for line in logs:
        print(line)


if __name__ == "__main__":
    main()
